version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
        context:
          - build-env-vars
          - docker-hub-creds

jobs:
  build:
    working_directory: .
    docker:
      - image: docker:latest
        auth:
          username: doct15
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: BUILD
        command: |
          docker build --quiet-false -t doct15/react1 .
      - run:
        name: PUSH
        command: |
          docker push doct15/react1

