version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      #- image: circleci/cci-demo-docker-primary:0.0.2
      - image: cimg/node:20.3.1
    #working_directory: .

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - setup_remote_docker

      # This should go into custom primary image, here's only for the sake of explanation

      - run:
          name: Debug stuff
          command: |
            pwd
            ls -Rl
            which docker
            docker -v
            docker version
            sudo docker version

      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t doct15/react1:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push doct15/react1:$TAG
            docker push doct15/react1:latest

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
