workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds

jobs:
  build:
    docker:
      - image: doct15/react1:ci2
        auth:
          username: doct15:  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
